### ISSUE TITLE
Adopt an RFC template

### ISSUE THREAD

**Issue by yegortimoshenko** [Holo-Host/rfcs#17]
Prior art:

- NixOS RFC template: https://github.com/nixos/rfcs/blob/master/0000-template.md
- Rust RFC template: https://github.com/rust-lang/rfcs/blob/master/0000-template.md
- ADR template by Michael Nygard: https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md

**Comment by paulbhartzog-holo** [comment]
> Previous art:
> 
> * NixOS RFC template: https://github.com/nixos/rfcs/blob/master/0000-template.md

I really like the NixOS one

**Comment by peeech** [comment]
My vote goes towards NixOS RFC template, too!
- NixOS RFC template: https://github.com/nixos/rfcs/blob/master/0000-template.md

**Comment by yegortimoshenko** [comment]
Closing based on discussion in #23.
