### ISSUE TITLE
Reorganize separation of concerns in Holo teams

### ISSUE THREAD

**Issue by mjbrisebois** [Holo-Host/rfcs#30]
CC @Holo-Host/central @Holo-Host/happy 

This is meant to be an RFC on the idea of rearranging responsibilities so that we can more efficiently merge code into master.

This first post is the result of a few minor discussions.  We should continue the conversation here so that all stakeholders can participate async, and so that it is nicely documented for future reference.

**hAppy Team** - will be responsible for projects that span Holochain + Hosting

- Holofuel (DNA + UI)
- hApp Store (DNA + UI)
- Communities ?
- DeepKey
- RAD Tools
- Persona
- Web SDK

**Holo Central** - will be responsible for projects that are only required for Hosting

- HPOS
  - HP Config
  - HP Admin (API + UI)
  - Envoy
  - Service Logger
  - Holo Hosting App (DNA + UI)
- HP Auth + Status
- Holo Router
- Resolver
- Chaperone

> **Summary of changes:** Holofuel DNA moves to hAppy, HP Admin UI and HHA DNA + UI move to Central

**Comment by jmday** [comment]
@artbrock @marycamacho I sense you should probably have visibility and opportunity to weigh in on this proposal.

**Comment by alastairong** [comment]
hAppy is also responsible for RAD tools and Persona

HoloCentral will eventually also be responsible for any app provider portal for deploying hApps for hosting. This will presumably have UI/UX needs.

**Comment by alastairong** [comment]
A couple of other points to log here from other discussions:
- We have an intent over time to evolve more E2E responsibility for the projects we are responsible for. 
  - For hAppy team this means becoming increasingly responsible for their own devops (e.g. the hosting for hosted hApp UIs). For  
  - For HoloCentral this means increasingly responsible for UX/UI
- For now there's been enough UX work on HP admin and Holo Hosting App that we don't need to solve the lack of specialised UX capability on HoloCentral
- There's a general awareness that HoloCentral hasn't been particularly close to our customer base and their experience, given other pulls. As we shift towards E2E responsibility HoloCentral needs to better understand our users. This starts with me as PO :)

**Comment by alastairong** [comment]
@SirRobLyon Would like your input here too

**Comment by alastairong** [comment]
@mjbrisebois On your summary of changes HHA DNA would also move to HoloCentral right?

**Comment by alastairong** [comment]
Re: HoloFuel - this is specifically the HoloFuel transactor hApp that would move over to hAppy team. Future components of the broader HoloFuel network might live in HoloCentral or hAppy depending. For example:
- Reserve accounts are likely to be a centralised and built by HoloCentral
- Mutual credit-based credit limit mechanisms might be implemented by HoloCentral or hAppy team depending on the scope / implementation

Also - Hosting quality of service calculators and autopilot are future projects under HoloCentral scope but not on this list which is focused on current concerns.

**Comment by SirRobLyon** [comment]
hAppy team discussed this yesterday during our overflow, and as far as the divvying up of responsibilities, I haven't heard any objections there.

I don't think anyone is strongly opposed, but my impression is there's a little tension in folks continuing forward async on this and not knowing what they're signing themselves up for exactly. So we have a request to connect the two teams synchronously, ideally with Art and Mary involved, to talk through the details. 

Some of the team's questions centered around, What are the expectations and timing of this? What are the next steps? How would this work for our designers weighing in on HoloCentral UI considerations? What's the priority and timing of this? There's work to be done to uncouple HoloFuel from HP Admin, where does that fall in our priorities?

**Comment by alastairong** [comment]
Great points @SirRobLyon Let’s discuss first so we can schedule a more targeted synchronous discussion

**Comment by alastairong** [comment]
@SirRobLyon Actually it's probably best if we discuss in here directly for transparency, rather than as a call. Can we compile a list of questions here?

**Comment by mjbrisebois** [comment]
> @alastairong For larger UX work I would propose that for now the wireframes are done by hAppy team and handed over to HoloCentral for implementation. We would prefer to minimise constant back-and-forth during the implementation itself though.

I don't see this working in practice.  Wireframes will be a collaborative process like any other part of development.  If one team is dependent on another team's members to accomplish their stories, we start to resemble a waterfall development model.  Is there a reason that all our UX/graphics expertise needs to be on hAppy team?

**Comment by alastairong** [comment]
@mjbrisebois Good point - I only meant short term since people changes take longer to handle. But yes long term we should have our own UX expertise if we UX scope that we are responsible for.

**Comment by alastairong** [comment]
CC: @Holo-Host/central @Holo-Host/happy

Mary and Art have highlighted that while Github is the right place for technical / architectural discussion it is definitely not the right place for a cross team organisational responsibilities discussion. For example Mary's notifications go to an old email account so she had no idea this was happening. And someone like Katie would have no idea that this is happening.

We should move this to Google Docs, which should still satisfy our need for documentation and collaboration. I can do it tomorrow unless there is a very good reason not to.

**Comment by mjbrisebois** [comment]
Currently, this is only about reorganizing technical responsibility so I am unaware of why Katie would have any concerns or input.

The absence of notifications does not seem like a good reason to abandon where the conversation belongs.  I do not get notifications either.

I'm very much against moving this to Google Docs; to me, that means it will disappear into oblivion.  I'm quite certain that my participation will drop significantly when I start thinking a conversation is ephemeral.

**Comment by alastairong** [comment]
Reorganising responsibility at the level of products / projects makes it an organisational concern rather than purely a technical one - as demonstrated by the discussion about having UX expertise within HoloCentral (and potentially devops in hAppy). Katie hasn't been part of this conversation but given her work on people management etc. she should at the very least be aware about the substance of this discussion.

Why do you feel Google Docs is ephemeral? The document will live in our org-wide Google drive for future reference.

**Comment by yegortimoshenko** [comment]
> Mary and Art view is that while Github is the right place for technical / architectural discussion it is not the right place for a cross team organisational responsibilities discussion. For example Mary's notifications go to an old email account so she had no idea this was happening. And someone like Katie would have no idea that this is happening.

I wonder if we could fix that first? They can add their new email address to <https://github.com/settings/emails>. That triggers a confirmation email to the new address. Once confirmed, they can update their notification email here: https://github.com/settings/notifications#primary_email_select_label

**Comment by alastairong** [comment]
Thanks Yegor. I think Mary should definitely do that since she should have visibility into Github and participate in some of the discussions that definitely do belong here.

It doesn't address the concern about where this discussion belongs though. This is a discussion that should be visible to some of our non-technical colleagues. Github is not accessible to them, while Google Docs is accessible to both technical and non-technical colleagues alike. I personally don't see how Google Docs is any more ephemeral than Github.

P.S. I'm open to other options than Google Docs. The key thing is about being accessible to both technical and non-technical colleagues.

**Comment by mjbrisebois** [comment]
> @alastairong Why do you feel Google Docs is ephemeral? The document will live in our org-wide Google drive for future reference.

**Google docs**
- can be trashed eventually by someone and we can only hope that it gets noticed before permanently deleted (if we defer to murphy's law here, we can assume this will happen)
- cannot be closed (archived) after being resolved.  A manual process is the only substitute which means many different processes will emerge.
- comments and conversation are harder to follow; when coupled with revisions, even harder.

**What we are not getting from Github issues**
- isolated sub-conversations
- decision tools
- revision history

PRs provide isolated sub-conversations and revision history, but I agree that not all stakeholders can participate there.

I hope we can find a tool that provides all these things without a large learning curve.  If only there were agent-centric decentralized apps to assist us with all these collaboration affairs ;)

**Comment by alastairong** [comment]
@mjbrisebois Per your discussion with hAppy team, please update OP to reflect Holo Web SDK responsibility being part of hAppy team "ideally".

**Comment by alastairong** [comment]
CC: @Holo-Host/central @Holo-Host/happy @jmday 

This is discussion now blocked because it is becoming a conversation about org structure, people, and timing/transition rather than about technical scope and we do not have the right people here for that conversation, nor is this the right forum for an org / people discussion.

As it is reasonably clear that both hAppy and HoloCentral are in agreement about the "ideal" separation of concerns, I think this conversation should now be closed and I will put it forward as a joint HoloCentral/hAppy team proposal for to be considered from an org / people / transition perspective.

Will close end of week if no objections.

**Comment by alastairong** [comment]
Will post link to org-wide conversation once I create it
